version: '3'

services:
  postgres:
    image: postgres:12.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hotel_booking
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      retries: 5
      timeout: 10s
  hotel-booking:
    build:
      context: .
    image: hotel-booking
    container_name: hotel-booking
    ports:
      - "8080:8080"
    depends_on:
      - postgres